name: CI

on:
 workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v2
    - name: Run a script
      run: echo "Running in DEV"
   

